### PR TITLE
Create wyr-pl.po

### PR DESCRIPTION
**Pull request by Pawonashi**
Beginning translating Wyrmsun to Polish

### CODE REVIEW

**Comment by Pawonashi** [comment]
Finished translating Dwarven Campaign to Polish in newly created Wyrmsun Polish translation file

**Comment by Andrettin** [comment]
Thanks for doing this, dziękuję! :)

**Comment by Pawonashi** [comment]
No problem, I can't wait for full support for translations. And it's nice to see some words in Polish from a developer :)

**Comment by Andrettin** [comment]
:) I have some Polish friends so I learned a bit from them.

I've improved the translation support now, so that things like the times of day, faction names and in-game button names are translated. I also allowed the partial translations to be chosen from the options menu (these changes are in the latest commits to Wyrmgus and Wyrmsun and in the current development version on Steam), so that the translations can be tested more easily.

I've added some new translated strings to the Portuguese translation, which could be useful as a reference regarding what is translatable now:
https://raw.githubusercontent.com/Andrettin/Wyrmsun/master/translations/wyr-pt.po

**Comment by Pawonashi** [comment]
No problem, I can't wait for full support for translations. And it's nice
to see some words in Polish from a developer :)

2016-10-21 13:45 GMT+02:00 Andrettin <notifications@github.com>:

**Pull request merged**
